version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    env_file:
      - .env
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
        db:
          condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DEBUG: ${DEBUG}
    volumes:
      - ./models:/app/models

volumes:
  postgres_data:
    driver: local